/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bec6e0",
        error: "#ba1a1a",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed-variant": "#003ea8",
        primary: "#000000",
        secondary: "#0051d5",
        "on-primary": "#ffffff",
        "surface-tint": "#565e74",
        "surface-variant": "#d3e4fe",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#fefcff",
        "surface-dim": "#cbdbf5",
        "outline-variant": "#c6c6cd",
        "surface-container-highest": "#d3e4fe",
        "on-background": "#0b1c30",
        "on-primary-fixed": "#131b2e",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#818486",
        "tertiary-fixed": "#e0e3e5",
        "inverse-primary": "#bec6e0",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed-variant": "#444749",
        "inverse-surface": "#213145",
        "secondary-container": "#316bf3",
        "on-surface": "#0b1c30",
        "on-secondary-fixed": "#00174b",
        "on-primary-container": "#7c839b",
        "primary-container": "#131b2e",
        "secondary-fixed": "#dbe1ff",
        outline: "#76777d",
        tertiary: "#000000",
        "tertiary-fixed-dim": "#c4c7c9",
        surface: "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#45464d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#191c1e",
        "inverse-on-surface": "#eaf1ff",
        background: "#f8f9ff",
        "on-tertiary-fixed": "#191c1e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "element-gap": "24px",
        gutter: "32px",
        "section-gap": "128px",
        "container-max": "1140px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        display: ["Hanken Grotesk", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["1.5rem", { lineHeight: "1.4", fontWeight: "600" }],
        display: ["4.5rem", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-code": ["0.875rem", { lineHeight: "1.5", fontWeight: "500" }],
        "body-lg": ["1.125rem", { lineHeight: "1.7", fontWeight: "400" }],
        "headline-lg": ["2.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["2rem", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
